version: "3.9"

services:
    web:
        build: .
        container_name: github-tags
        command: sh -c "yarn prisma db push && yarn dev"
        environment:
            DATABASE_URL: postgresql://postgres:postgres@db/tests
        depends_on:
            - db
        links:
            - db
        ports:
            - 3000:3000
        volumes:
            - ./src:/usr/app/src
            - ./__tests__:/usr/app/__tests__

    db:
        image: postgres:13
        restart: always
        container_name: github-tags-db-dev
        ports:
            - "5433:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: tests
